[package]
name = "libzeropool-wasm"
version = "0.1.3"
authors = ["Dmitry Vdovin <voidxnull@gmail.com>"]
repository = "https://github.com/zeropoolnetwork/libzeropool-wasm/"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.71"

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }

libzeropool = { git = "https://github.com/zeropoolnetwork/libzeropool.git" }
getrandom = { version = "0.2.2", features = ["js"] }
fawkes-crypto = "3.0.3"
sha2 = "0.9.3"
bs58 = "0.4.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.21"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
