[workspace]
members = [
    "libzeropool-rs-wasm",
    "libzeropool-rs",
    "libzeropool-rs-node",
]

[patch.crates-io]
fawkes-crypto-bellman_ce = { git = "https://github.com/voidxnull/phase2-bn254" }
