[package]
name = "libzeropool-rs-node"
version = "0.1.0"
authors = ["Dmitry Vdovin <voidxnull@gmail.com>"]
repository = "https://github.com/zeropoolnetwork/libzeropool-wasm/"
license = "MIT OR Apache-2.0"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libzeropool-rs = { path = "../libzeropool-rs" }

[dependencies.neon]
git = "https://github.com/neon-bindings/neon.git"
default-features = false
features = ["napi-6"]
