[package]
name = "libzeropool-rs-node"
version = "0.1.0"
authors = ["Dmitry Vdovin <voidxnull@gmail.com>"]
repository = "https://github.com/zeropoolnetwork/libzeropool-wasm/"
license = "MIT OR Apache-2.0"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libzeropool-rs = { path = "../libzeropool-rs" }
neon-serde = "0.4.0"
serde = "1.0.127"

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]
